#include "opencl_source_map.hpp" 
namespace MNN { 
#ifndef MNN_OPENCL_BUFFER_CLOSED
const char* fav2_buf = 
"#ifndef D_HEAD\n"
"#define D_HEAD 128\n"
"#endif\n"
"#define BLOCK_SIZE_M 32\n"
"#define BLOCK_SIZE_N 32\n"
"#define FLT_MAX 3.402823466e+38F\n"
"// Load a tile for fixed (batch,head) from [B,S,H,D] layout.\n"
"// base_offset=b*S*H*D_HEAD+h*D_HEAD\n"
"// stride_seq=H*D_HEAD (floats between consecutive tokens for this head)\n"
"// start_row=first token index of this tile\n"
"void load_global_tile_mnn(\n"
" __global const float *src,\n"
" __local float *dst,\n"
" const int base_offset,\n"
" const int stride_seq,\n"
" const int start_row,\n"
" const int num_rows,\n"
" const int max_rows,\n"
" const int local_id,\n"
" const int wg_size\n"
") {\n"
" const int d_head_vec=D_HEAD/4;\n"
" const int total_elements=num_rows*d_head_vec;\n"
" for (int i=local_id; i<total_elements; i += wg_size) {\n"
" int r=i/d_head_vec;\n"
" int c=i % d_head_vec;\n"
" int global_row=start_row+r;\n"
" int dst_offset=(r*D_HEAD)+c*4;\n"
" int src_offset=base_offset+global_row*stride_seq+c*4;\n"
" if (global_row<max_rows) {\n"
" float4 val=vload4(0,src+src_offset);\n"
" vstore4(val,0,dst+dst_offset);\n"
" } else {\n"
" vstore4((float4)(0.0f),0,dst+dst_offset);\n"
" }\n"
" }\n"
"}\n"
"// Q,K,V,O: float32[B,S,H,D] (MNN layout: seq before heads)\n"
"__kernel void flash_attention_v2_mnn_fwd(\n"
" __global const float *Q,\n"
" __global const float *K,\n"
" __global const float *V,\n"
" __global float *O,\n"
" const int B,\n"
" const int H,\n"
" const int L,\n"
" const int S,\n"
" const float scale,\n"
" const int is_causal\n"
") {\n"
" const int batch_idx=get_global_id(1);\n"
" const int head_idx=get_global_id(2);\n"
" const int q_block_idx=get_group_id(0);\n"
" if (batch_idx >= B || head_idx >= H) return;\n"
" // [B,S,H,D]: element(b,s,h,d)=b*S*H*D+s*H*D+h*D+d\n"
" // for fixed (b,h): base=b*S*H*D+h*D,token stride=H*D\n"
" const int stride_Q=H*D_HEAD;\n"
" const int stride_K=H*D_HEAD;\n"
" const int base_Q=batch_idx*L*H*D_HEAD+head_idx*D_HEAD;\n"
" const int base_K=batch_idx*S*H*D_HEAD+head_idx*D_HEAD;\n"
" const int tid=get_local_id(0);\n"
" const int wg_size=get_local_size(0);\n"
" __local float Q_tile[BLOCK_SIZE_M*D_HEAD];\n"
" __local float K_tile[BLOCK_SIZE_N*D_HEAD];\n"
" __local float V_tile[BLOCK_SIZE_N*D_HEAD];\n"
" float m_i=-FLT_MAX;\n"
" float l_i=0.0f;\n"
" float4 O_acc4[D_HEAD/4];\n"
" for (int d=0; d<D_HEAD/4; ++d) O_acc4[d]=(float4)(0.0f);\n"
" const int q_start_row=q_block_idx*BLOCK_SIZE_M;\n"
" const int num_q_rows=(q_start_row+BLOCK_SIZE_M>L) ? (L-q_start_row) : BLOCK_SIZE_M;\n"
" load_global_tile_mnn(Q,Q_tile,base_Q,stride_Q,q_start_row,BLOCK_SIZE_M,L,tid,wg_size);\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" const int num_kv_blocks=(S+BLOCK_SIZE_N-1)/BLOCK_SIZE_N;\n"
" for (int k_block=0; k_block<num_kv_blocks; ++k_block) {\n"
" const int k_start_row=k_block*BLOCK_SIZE_N;\n"
" const int num_k_rows=(k_start_row+BLOCK_SIZE_N>S) ? (S-k_start_row) : BLOCK_SIZE_N;\n"
" if (is_causal && k_start_row>(q_start_row+BLOCK_SIZE_M-1)) break;\n"
" load_global_tile_mnn(K,K_tile,base_K,stride_K,k_start_row,BLOCK_SIZE_N,S,tid,wg_size);\n"
" load_global_tile_mnn(V,V_tile,base_K,stride_K,k_start_row,BLOCK_SIZE_N,S,tid,wg_size);\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" if (tid<BLOCK_SIZE_M && tid<num_q_rows) {\n"
" float scores[BLOCK_SIZE_N];\n"
" float m_block=-FLT_MAX;\n"
" const int q_off=tid*D_HEAD;\n"
" for (int j=0; j<num_k_rows; ++j) {\n"
" if (is_causal && (k_start_row+j)>(q_start_row+tid)) {\n"
" scores[j]=-FLT_MAX;\n"
" continue;\n"
" }\n"
" float s=0.0f;\n"
" const int k_off=j*D_HEAD;\n"
" for (int d=0; d<D_HEAD/4; ++d) {\n"
" s += dot(vload4(d,Q_tile+q_off),\n"
" vload4(d,K_tile+k_off));\n"
" }\n"
" scores[j]=s*scale;\n"
" m_block=fmax(m_block,scores[j]);\n"
" }\n"
" float m_new=fmax(m_i,m_block);\n"
" float alpha=exp(m_i-m_new);\n"
" for (int d=0; d<D_HEAD/4; ++d) O_acc4[d] *= alpha;\n"
" float block_l=0.0f;\n"
" for (int j=0; j<num_k_rows; ++j) {\n"
" float e=exp(scores[j]-m_new);\n"
" const int v_off=j*D_HEAD;\n"
" for (int d=0; d<D_HEAD/4; ++d) {\n"
" O_acc4[d] += e*vload4(d,V_tile+v_off);\n"
" }\n"
" block_l += e;\n"
" }\n"
" l_i=l_i*alpha+block_l;\n"
" m_i=m_new;\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" }\n"
" if (tid<BLOCK_SIZE_M && tid<num_q_rows) {\n"
" // write [B,S,H,D]: base_Q+token*stride_Q+d\n"
" const int global_out_base=base_Q+(q_start_row+tid)*stride_Q;\n"
" const float inv_l=1.0f/l_i;\n"
" for (int d=0; d<D_HEAD/4; ++d) {\n"
" vstore4(O_acc4[d]*inv_l,d,O+global_out_base);\n"
" }\n"
" }\n"
"}\n"
;
#endif
}
