#include "opencl_source_map.hpp" 
namespace MNN { 
#ifndef MNN_OPENCL_BUFFER_CLOSED
const char* fav2_buf = 
"#ifdef cl_khr_fp16\n"
"#pragma OPENCL EXTENSION cl_khr_fp16 : enable\n"
"#endif\n"
"#ifndef D_HEAD\n"
"#define D_HEAD 128\n"
"#endif\n"
"#ifndef BLOCK_SIZE_M\n"
"#define BLOCK_SIZE_M 32\n"
"#endif\n"
"#ifndef BLOCK_SIZE_N\n"
"#define BLOCK_SIZE_N 32\n"
"#endif\n"
"#ifndef THREADS_PER_ROW\n"
"#define THREADS_PER_ROW 4\n"
"#endif\n"
"#ifndef PRECISION_COMPUTE\n"
"#define PRECISION_COMPUTE float\n"
"#endif\n"
"#ifndef PRECISION_COMPUTE4\n"
"#define PRECISION_COMPUTE4 float4\n"
"#endif\n"
"#ifndef CONVERT_PRECISION_COMPUTE4\n"
"#define CONVERT_PRECISION_COMPUTE4 convert_float4\n"
"#endif\n"
"#define WG_SIZE (BLOCK_SIZE_M*THREADS_PER_ROW)\n"
"#define D_SLICE (D_HEAD/THREADS_PER_ROW)\n"
"#define D_SLICE_VEC (D_SLICE/4)\n"
"#define FLT_MAX 3.402823466e+38F\n"
"void load_global_tile_compute(\n"
" __global const float *src,\n"
" __local PRECISION_COMPUTE *dst,\n"
" const int base_offset,\n"
" const int stride_seq,\n"
" const int start_row,\n"
" const int num_rows,\n"
" const int max_rows,\n"
" const int local_id\n"
") {\n"
" const int d_head_vec=D_HEAD/4;\n"
" const int total_elements=num_rows*d_head_vec;\n"
" for (int i=local_id; i<total_elements; i += WG_SIZE) {\n"
" int r=i/d_head_vec;\n"
" int c=i % d_head_vec;\n"
" int global_row=start_row+r;\n"
" int dst_offset=r*D_HEAD+c*4;\n"
" int src_offset=base_offset+global_row*stride_seq+c*4;\n"
" PRECISION_COMPUTE4 val;\n"
" if (global_row<max_rows) {\n"
" val=CONVERT_PRECISION_COMPUTE4(vload4(0,src+src_offset));\n"
" } else {\n"
" val=CONVERT_PRECISION_COMPUTE4((float4)(0.0f));\n"
" }\n"
" vstore4(val,0,dst+dst_offset);\n"
" }\n"
"}\n"
"void load_global_tile_fp32(\n"
" __global const float *src,\n"
" __local float *dst,\n"
" const int base_offset,\n"
" const int stride_seq,\n"
" const int start_row,\n"
" const int num_rows,\n"
" const int max_rows,\n"
" const int local_id\n"
") {\n"
" const int d_head_vec=D_HEAD/4;\n"
" const int total_elements=num_rows*d_head_vec;\n"
" for (int i=local_id; i<total_elements; i += WG_SIZE) {\n"
" int r=i/d_head_vec;\n"
" int c=i % d_head_vec;\n"
" int global_row=start_row+r;\n"
" int dst_offset=r*D_HEAD+c*4;\n"
" int src_offset=base_offset+global_row*stride_seq+c*4;\n"
" if (global_row<max_rows) {\n"
" vstore4(vload4(0,src+src_offset),0,dst+dst_offset);\n"
" } else {\n"
" vstore4((float4)(0.0f),0,dst+dst_offset);\n"
" }\n"
" }\n"
"}\n"
"__kernel void flash_attention_v2_mnn_fwd(\n"
" __global const float *Q,\n"
" __global const float *K,\n"
" __global const float *V,\n"
" __global float *O,\n"
" const int B,\n"
" const int H,\n"
" const int L,\n"
" const int S,\n"
" const float scale,\n"
" const int is_causal\n"
") {\n"
" const int batch_idx=get_global_id(1);\n"
" const int head_idx=get_global_id(2);\n"
" const int q_block_idx=get_group_id(0);\n"
" if (batch_idx >= B || head_idx >= H) return;\n"
" const int tid=get_local_id(0);\n"
" const int row_id=tid/THREADS_PER_ROW;\n"
" const int d_id=tid % THREADS_PER_ROW;\n"
" const int d_start=d_id*D_SLICE;\n"
" const int d_start_vec=d_id*D_SLICE_VEC;\n"
" const int stride_seq=H*D_HEAD;\n"
" const int base_Q=batch_idx*L*stride_seq+head_idx*D_HEAD;\n"
" const int base_K=batch_idx*S*stride_seq+head_idx*D_HEAD;\n"
" __local PRECISION_COMPUTE Q_tile[BLOCK_SIZE_M*D_HEAD];\n"
" __local float KV_tile_fp32[BLOCK_SIZE_N*D_HEAD];\n"
" float m_i=-FLT_MAX;\n"
" float l_i=0.0f;\n"
" float4 O_acc4[D_SLICE_VEC];\n"
" for (int d=0; d<D_SLICE_VEC; ++d) O_acc4[d]=(float4)(0.0f);\n"
" const int q_start_row=q_block_idx*BLOCK_SIZE_M;\n"
" const int num_q_rows=min(BLOCK_SIZE_M,L-q_start_row);\n"
" load_global_tile_compute(Q,Q_tile,base_Q,stride_seq,q_start_row,BLOCK_SIZE_M,L,tid);\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" const int num_kv_blocks=(S+BLOCK_SIZE_N-1)/BLOCK_SIZE_N;\n"
" for (int k_block=0; k_block<num_kv_blocks; ++k_block) {\n"
" const int k_start_row=k_block*BLOCK_SIZE_N;\n"
" const int num_k_rows=min(BLOCK_SIZE_N,S-k_start_row);\n"
" if (is_causal && k_start_row>(q_start_row+BLOCK_SIZE_M-1)) break;\n"
" load_global_tile_compute(K,(__local PRECISION_COMPUTE *)KV_tile_fp32,base_K,stride_seq,k_start_row,BLOCK_SIZE_N,S,tid);\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" __local PRECISION_COMPUTE *K_tile=(__local PRECISION_COMPUTE *)KV_tile_fp32;\n"
" float scores[BLOCK_SIZE_N];\n"
" float m_block=-FLT_MAX;\n"
" if (row_id<num_q_rows) {\n"
" const int q_off=row_id*D_HEAD;\n"
" for (int j=0; j<num_k_rows; ++j) {\n"
" if (is_causal && (k_start_row+j)>(q_start_row+row_id)) {\n"
" scores[j]=-FLT_MAX;\n"
" continue;\n"
" }\n"
" float s=0.0f;\n"
" const int k_off=j*D_HEAD;\n"
" for (int d=0; d<D_HEAD/4; ++d) {\n"
" float4 q4=convert_float4(vload4(d,Q_tile+q_off));\n"
" float4 k4=convert_float4(vload4(d,K_tile+k_off));\n"
" s += dot(q4,k4);\n"
" }\n"
" scores[j]=s*scale;\n"
" m_block=fmax(m_block,scores[j]);\n"
" }\n"
" float m_new=fmax(m_i,m_block);\n"
" float alpha=exp(m_i-m_new);\n"
" for (int d=0; d<D_SLICE_VEC; ++d) O_acc4[d] *= alpha;\n"
" float block_l=0.0f;\n"
" for (int j=0; j<num_k_rows; ++j) {\n"
" scores[j]=exp(scores[j]-m_new);\n"
" block_l += scores[j];\n"
" }\n"
" l_i=l_i*alpha+block_l;\n"
" m_i=m_new;\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" load_global_tile_fp32(V,KV_tile_fp32,base_K,stride_seq,k_start_row,BLOCK_SIZE_N,S,tid);\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" if (row_id<num_q_rows) {\n"
" for (int j=0; j<num_k_rows; ++j) {\n"
" const float e=scores[j];\n"
" const int v_off=j*D_HEAD+d_start;\n"
"#pragma unroll\n"
" for (int d=0; d<D_SLICE_VEC; ++d) {\n"
" O_acc4[d] += e*vload4(d,KV_tile_fp32+v_off);\n"
" }\n"
" }\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" }\n"
" if (row_id<num_q_rows) {\n"
" const int global_out_base=base_Q+(q_start_row+row_id)*stride_seq;\n"
" const float inv_l=1.0f/l_i;\n"
"#pragma unroll\n"
" for (int d=0; d<D_SLICE_VEC; ++d) {\n"
" vstore4(O_acc4[d]*inv_l,d_start_vec+d,O+global_out_base);\n"
" }\n"
" }\n"
"}\n"
;
#endif
}
